default:
	valac --vapidir=vapi \
	--pkg=drawkit \
	--pkg=glesv2 \
	--pkg=wayland-client \
	--pkg=egl \
	--pkg=liblayershell \
	-X -I/home/nicholas/Dokumenter/layer-shell-experiments/liblayershell \
	-X -I/home/nicholas/Dokumenter/layer-shell-experiments/src \
	-X -L/home/nicholas/Dokumenter/layer-shell-experiments/liblayershell/build \
	-X -llayershell \
	src/*.vala
	
	