default:
	gcc -o panel *.c \
	-lEGL \
	-lGLESv2 \
	-lwayland-client \
	-lpng \
	-L/home/nicholas/Dokumenter/layer-shell-experiments/liblayershell/build -llayershell \
	-Wl,-rpath=/home/nicholas/Dokumenter/layer-shell-experiments/liblayershell/build