%global srcname lumenshell

# C++ Wayfire plugins (desktop-peek, curtain-peek, startup-zoom, default-focus)
# need Wayfire >= 0.10 + wlroots dev headers, which are not always packaged.
# They are OFF by default; build with `--with wayfire_plugins` to enable.
#   rpmbuild -ba packaging/rpm/lumenshell.spec --with wayfire_plugins
%bcond_with wayfire_plugins

Name:           %{srcname}
Version:        1.0
Release:        1%{?dist}
Summary:        ChromeOS-inspired Wayland desktop shell

License:        GPL-3.0-or-later
URL:            https://github.com/nicholas/LumenShell
# Generated by packaging/make-tarball.sh (git archive of the worktree).
Source0:        %{srcname}-%{version}.tar.gz

BuildRequires:  gcc
BuildRequires:  gcc-c++
BuildRequires:  make
BuildRequires:  meson
BuildRequires:  ninja-build
BuildRequires:  pkgconfig
BuildRequires:  vala
BuildRequires:  pkgconfig(glib-2.0)
BuildRequires:  pkgconfig(gio-2.0)
BuildRequires:  pkgconfig(gio-unix-2.0)
BuildRequires:  pkgconfig(gobject-2.0)
BuildRequires:  pkgconfig(gee-0.8)
BuildRequires:  pkgconfig(json-glib-1.0)
BuildRequires:  pkgconfig(gtk4)
BuildRequires:  pkgconfig(gtk4-wayland)
BuildRequires:  pkgconfig(gtk4-layer-shell-0)
BuildRequires:  pkgconfig(wayland-client)
BuildRequires:  pkgconfig(wayland-egl)
BuildRequires:  pkgconfig(egl)
BuildRequires:  pkgconfig(glesv2)
BuildRequires:  pkgconfig(xkbcommon)
BuildRequires:  pkgconfig(libxml-2.0)
BuildRequires:  freetype-devel
%if %{with wayfire_plugins}
BuildRequires:  pkgconfig(wayfire)
BuildRequires:  pkgconfig(wlroots-0.19)
%endif

# Runtime compositor + layer-shell stack. The lumen-* binaries are useless
# without a Wayfire session to host them.
Requires:       wayfire
Requires:       gtk4-layer-shell

%description
LumenShell is a ChromeOS-inspired desktop shell for Wayland. It runs on the
Wayfire compositor as a collection of small gtk4-layer-shell apps written in
Vala: a bottom panel, an app-drawer desktop, an on-screen display, a
notification daemon, and a settings app. Installing this package adds a
"LumenShell" entry to the display manager's session menu.

%prep
%autosetup -n %{srcname}-%{version}

%build
%meson \
    -Dwith_desktop_peek=%{?with_wayfire_plugins:true}%{!?with_wayfire_plugins:false} \
    -Dwith_curtain_peek=%{?with_wayfire_plugins:true}%{!?with_wayfire_plugins:false} \
    -Dwith_startup_zoom=%{?with_wayfire_plugins:true}%{!?with_wayfire_plugins:false}
%meson_build

%install
%meson_install

%files
%license LICENSE
%doc README.md
%{_bindir}/lumen-osd
%{_bindir}/lumen-osdctl
%{_bindir}/lumen-panel
%{_bindir}/lumen-desktop
%{_bindir}/lumen-notifications
%{_bindir}/lumen-settings
%{_bindir}/start-lumenshell
%{_datadir}/lumen-osd/
%{_datadir}/lumen-panel/
%{_datadir}/lumen-notifications/
%{_datadir}/lumen-settings/
%{_datadir}/lumenshell/
%{_datadir}/applications/org.lumenshell.Settings.desktop
%{_datadir}/wayland-sessions/lumenshell.desktop
%if %{with wayfire_plugins}
%{_libdir}/wayfire/libwayfire-*.so
%{_datadir}/wayfire/metadata/wayfire-*.xml
%endif

%changelog
* Tue Jun 09 2026 LumenShell <noreply@lumenshell> - 1.0-1
- Initial RPM packaging.
